package model;

/**
 * Created by sebastian on 23.01.15.
 */
public enum Language {
    ABAP("abap"),
    ActionScript("actionscript"),
    ADA("ada"),
    ApacheConf("apache_conf"),
    AppleScript("applescript"),
    ASCIIDoc("asciidoc"),
    Assemblyx86("assembly_x86"),
    AutoHotKey("autohotkey"),
    BatchFile("batchfile"),
    C_CPP("c_cpp"),
    CSharp("csharp"),
    C9SearchResults("c9search"),
    Clojure("clojure"),
    Cobol("cobol"),
    CoffeeScript("coffee"),
    ColdFusion("coldfusion"),
    CSS("css"),
    Curly("curly"),
    D("d"),
    Dart("dart"),
    Diff("diff"),
    Django("django"),
    Dot("dot"),
    EJS("ejs"),
    Erlang("erlang"),
    Forth("forth"),
    FreeMarker("ftl"),
    GLSL("glsl"),
    Go("golang"),
    Groovy("groovy"),
    HAML("haml"),
    Handlebars("handlebars"),
    Haskell("haskell"),
    haXe("haxe"),
    HTML("html"),
    HTMLRuby("html_ruby"),
    INI("ini"),
    Jack("jack"),
    Jade("jade"),
    Java("java"),
    JavaScript("javascript"),
    JSON("json"),
    JSONiq("jsoniq"),
    JSP("jsp"),
    JSX("jsx"),
    Julia("julia"),
    LaTex("latex"),
    LESS("less"),
    Liquid("liquid"),
    Lisp("lisp"),
    LiveScript("livescript"),
    LogiQL("logiql"),
    LSL("lsl"),
    Lua("lua"),
    LuaPage("luapage"),
    Lucene("lucene"),
    Makefile("makefile"),
    Markdown("markdown"),
    MATLAB("matlab"),
    MEL("mel"),
    MUSHCode("mushcode"),
    MySQL("mysql"),
    Nix("nix"),
    ObjectiveC("objectivec"),
    OCaml("ocaml"),
    Pascal("pascal"),
    Perl("perl"),
    pgSQL("pgsql"),
    PHP("php"),
    PlainText("plain_text"),
    POVRay("povray"),
    Powershell("powershell"),
    Prolog("prolog"),
    Properties("properties"),
    Protobuf("protobuf"),
    Python("python"),
    R("r"),
    RDoc("rdoc"),
    RHTML("rhtml"),
    Ruby("ruby"),
    Rust("rust"),
    SASS("sass"),
    SCAD("scad"),
    Scala("scala"),
    Scheme("scheme"),
    SCSS("scss"),
    Shell("sh"),
    SJS("sjs"),
    Snippets("snippets"),
    SoyTemplate("soy_template"),
    Space("space"),
    SQL("sql"),
    Stylus("stylus"),
    SVG("svg"),
    Swift("swift"),
    Tcl("tcl"),
    Tex("text"),
    Text("text"),
    Textile("textile"),
    Toml("toml"),
    Twig("twig"),
    Typescript("typescript"),
    VBScript("vbscript"),
    Velocity("velocity"),
    Verilog("verilog"),
    VHDL("vhdl"),
    XML("xml"),
    XQuery("xquery"),
    YAML("yaml");



    private final String text;

    private Language(final String text) {
        this.text = text;
    }

    @Override
    public String toString() {
        return this.text;
    }
}
