/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sebastian' at '11.01.15 15:54' with Gradle 1.12
 *
 * @author sebastian, @date 11.01.15 15:54
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
